[package]
name = "hash-list"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nanoid = "0.4.0"
sha3 = "0.10.5"
hex = "0.4.3"
json-writer = "0.2.0"
clap = { version = "4.0.9", features = ["derive"] }
